### ISSUE TITLE
Client Key

### ISSUE THREAD

**Issue by erenoglu** [cali-95/LGTVLinuxCompanion#1]
Hi, could you explain what is the Client Key command line option? I tried to feed it with my ssh key, ssh private key, other certificate and its key, but nothing works. TV gives a message if I authorize, I do, but the LGTVLinuxCompanion throws an exception:

> Traceback (most recent call last):
>   File "LGTVLinuxCompanion/./lg_tv_linux_companion.py", line 192, in <module>
>     main()
>   File "LGTVLinuxCompanion/./lg_tv_linux_companion.py", line 186, in main
>     init(args)
>   File "LGTVLinuxCompanion/./lg_tv_linux_companion.py", line 109, in init
>     clean_up_and_raise_exception("invalid client_key")
>   File "LGTVLinuxCompanion/./lg_tv_linux_companion.py", line 182, in clean_up_and_raise_exception
>     raise Exception(exception_message)
> Exception: invalid client_key
>

**Comment by tibi22** [comment]
It's the LG connection client key (a key that you receive once you approve the connection to the TV and can use again for the next connections). You can get it from the logs here: https://github.com/cali-95/LGTVLinuxCompanion/blob/main/lg_tv_linux_companion.py#L108C5-L108C5

So run the script once with the wrong key and then check the logs for it.

**Comment by cali-95** [comment]
@tibi22  thanks for your answer.
