### ISSUE TITLE
Suggestions to automatize the process

### ISSUE THREAD

**Issue by fulalas** [cali-95/LGTVLinuxCompanion#2]
Hi,

Thanks a lot for porting this to Python.

I would like to improve this idea by suggesting a way to automatize the whole process. In other words, when the computer is idle the TV screen will turn off automatically, and when the system receives input from the mouse/keyboard/etc the TV screen will turn on automatically.

The solution I found so far works nice -- I make tiny changes in your python script (here's the updated version: [lg_tv_linux_companion.py.zip](https://github.com/cali-95/LGTVLinuxCompanion/files/13537494/lg_tv_linux_companion.py.zip))

1. Create `/opt/lg-companion`
2. Put the python script in `/opt/lg-companion`
3. Create text file `client-key` file `/opt/lg-companion`
4. Create text file `ip` file in `/opt/lg-companion`

Put your TV client key and IP inside each file above.

Now:

1. Create text file `/etc/acpi/events/monitor-off` and put this inside:  

```
event=jack/videoout VIDEOOUT unplug
action=/opt/lg-companion/lg_tv_linux_companion.py -c turnOffScreen -k $(cat /opt/lg-companion/client-key) -t $(cat /opt/lg-companion/ip)
```
2. Create text file `/etc/acpi/events/monitor-on` and put this inside:
```
event=jack/videoout VIDEOOUT plug
action=/opt/lg-companion/lg_tv_linux_companion.py -c turnOnScreen -k $(cat /opt/lg-companion/client-key) -t $(cat /opt/lg-companion/ip)
```

These `jack/videoout VIDEOOUT unplug` and `jack/videoout VIDEOOUT plug` events may be different according to the machine, so one way to get it right in case the ones I provided don't work is to set your system to turn off the display in 1 minute or less and run `acpi_listen` and wait. It will show which events you need.

Now just reboot and experience the TV behaving as a monitor :)

P.S.: there's only one minor thing that I haven't tried to fix: every time you reboot the machine the TV screen will turn off, so you need to press any button in the remote control to wake it up or wait until the boot process finishes so you can provide some input in the system to wake up the TV.

**Comment by cali-95** [comment]
Thank you for you suggestion. I will try it.

**Comment by hamoid** [comment]
Hi! I think this should be optional. 

In my case there's no mouse or keyboard, but it's an artwork running custom software. I want my software to decide when to turn the display on (once my software is already running) and off (right before shutting down a few hours later).

Thank you for sharing the Linux version :)

**Comment by cali-95** [comment]
I included your suggestion in the repo.

**Comment by fulalas** [comment]
Great! :)
