### ISSUE TITLE
A typo in command_mapping?

### ISSUE THREAD

**Issue by hamoid** [cali-95/LGTVLinuxCompanion#3]
Hi! I haven't even tried the program yet but I noticed this in the code:

    "turnOnSystem": "system/turnOff",
    "turnOffSystem": "system/turnOn",

Is that expected?

At https://github.com/cali-95/LGTVLinuxCompanion/blob/main/lg_tv_linux_companion.py#L44

And a question: if one turns off the system, can it be turned back on? Or does it turn off the API?

Cheers!

**Comment by cali-95** [comment]
thanks for the hint.
I removed the "system turn on" command, because in https://github.com/JPersson77/LGTVCompanion/blob/d3aad09d07593ed734aae40a092d86b27b43e93e/Common/LgApi.h it is also not included.
the screen turn off/on commands work fine.
