### ISSUE TITLE
Issue getting it to work correctly on start up and shut down

### ISSUE THREAD

**Issue by icrackiphone** [cali-95/LGTVLinuxCompanion#4]
Hey man I just recently got into linux on my main pc. I have a lg c3 TV that I use as my main monitor. I have the normal windows version of this installed and working great. I've ran through the set up for this and it does appear to work that way. Eg I get the pop up to confirm on my TV, the screen goes black when doing the final commands and wakes with the remote again. However I'm struggling with getting it working with the automated steps. Sleeping and waking the pc shows the jack/videoout plug and unplug events when running acpi command but sleeping the pc the TV stays on and shows the no input screen. So I'm not sure if those are the correct events I should be using for this program. Turning the TV off and on with its remote while running the listen command doesn't show any readouts after the fact. I am very new to Linux so if I'm missing something stupid please let me know. Other than that install and everything is smooth and fairly easy to understand for a newb such as myself lol.

**Comment by cali-95** [comment]
Hi, your setup sounds about right. Depending on your linux distributions some things can be different. Which distributions are you using (Ubuntu, Mint, ...)? To debug the issue you should check if the triggers are working. E.g. change the action in `/etc/acpi/events/monitor_off` to `echo "off" >> /tmp/debug` (without ``) and reboot the pc. This action only creates a file named debug in /tmp. If the file is created when the pc goes to sleep, the "off" trigger is working, otherwise the path for acpi events may be different on your distro.

**Comment by icrackiphone** [comment]
Thanks for the reply! I am using Linux mint. Latest version and kernel and
all that. I will try your debugging ideas in the next day or so and get
back to you. Thanks for the help

**Comment by icrackiphone** [comment]
Okay sorry for the long wait. I finally got some more time to sit down and
fiddle with it. I did the steps you showed above and it did create the file
in /tmp. Just a blank file called debug. So the off trigger does things. I
did a clean reinstall of the whole thing today and I noticed that in the
folder my run_in_venv.sh has a .dist after the .sh. first noticed when the
final chmod command didn't work and makes sense the file name was wrong. I
renamed it and removed the .dist and the command worked fine and the file
name also matches what is in the files in /etc/acpi. Should I not have
changed that and changed the acpi files to reflect the .dist ending?

**Comment by icrackiphone** [comment]
Another thing I noticed just now is the monitor off.dist in the lg
companion folder and the monitor off in action events are different. The
one in the companion folder has the username and directory as the_user and
the_dir. While the one in events has those filed out. Do they need to match
with the proper username and directory?

**Comment by cali-95** [comment]
I added one missing command in the readme file.
The .dist files are only templates and aren`t changed. After initialization only the non-dist files are needed.
