### ISSUE TITLE
turnOnSystem and turnOffSystem commands

### ISSUE THREAD

**Issue by erenoglu** [cali-95/LGTVLinuxCompanion#5]
Hi, I'm using the tool for turning on and off the screen and it's working great.
But I also tried the turnOffSystem and turnOnSystem commands but they dont do anything.  Is there some settings that I need to change?

Issue is when the screen is Off, after some time, the TV goes to Always Ready mode (white led standby mode). From this mode, screen on command doesn't wake it up, and neither turnOnSystem. 

Btw, the turnOffSystem command does work and it turns off the TV and led goes to white (Always Ready mode standby).

Any clues why turnOnSystem may not work?

**Comment by erenoglu** [comment]
Btw, I checked network connectivity while TV is in this white led always ready mode, the TV responds to pings just fine. Just does not react to turnOnSystem command?  Does it require a different key than turnOnScreen command?

as a test, the LG Thinq app on the phone turns on and off w/o any issues.

**Comment by erenoglu** [comment]
Now I see below in the log.txt:

> 2024-03-17 21:21:39,314 - INFO - run 'turnOnSystem' command
> 2024-03-17 21:21:39,319 - DEBUG - {"type":"error","id":42,"error":"404 no such service or method","payload":{}}
> 2024-03-17 21:21:39,323 - INFO - cleanup finished

**Comment by cali-95** [comment]
checkout out https://github.com/cali-95/LGTVLinuxCompanion/issues/3. If you have time for it, you can try to find the right command for turing on in the code of the app or by intercepting the network traffic between the app and the TV.
