### ISSUE TITLE
turnOnSystem does not work

### ISSUE THREAD

**Issue by Wektory** [cali-95/LGTVLinuxCompanion#6]
Hi, I followed your guide, but the turnOnSystem argument does not work for me.
Automatic turnOffSystem (auto power off the tv) work well, but then the TV does not turn on automatic, just manually with the remote. 
Can you help please what could be the problem?
Thanks for reply.

I am blind actually, I am reading now that turnOnSystem is not possible with use this method, only turnOff, right?

**Comment by cali-95** [comment]
you can try the points of section Troubleshooting of https://github.com/JPersson77/LGTVCompanion. If it does not help, I have no fix.
