### ISSUE TITLE
no module named websockets

### ISSUE THREAD

**Issue by xpusostomos** [cali-95/LGTVLinuxCompanion#7]
The above error when trying to run the script that the instructions generate. I suppose it lacks some python package maybe, but boy I wish linux software was written so mere mortals could just run it without having to become an expert in stuff, just to start it  up. Would it be so hard even to have a simple install script that asks you questions on the command line, and does what is necessary?

**Comment by cali-95** [comment]
please follow the readme. To fix your current problem, run `pip install -r requirements.txt` in the root folder of the cloned git repo.
